import { Project, Source, Tag, Category, Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    brandName: 'Context OS',
    tagline: 'SaaS for Context Management',
    dashboard: 'Dashboard',
    projects: 'Projects',
    library: 'Library',
    tags: 'Tags',
    search: 'Search',
    export: 'Export Context',
    settings: 'Settings',
    capture: 'Capture',
    save: 'Save',
    addSource: 'Add Source',
    quickCapture: 'Quick Capture',
    quickCapturePlaceholder: 'Paste a URL, GitHub repo, video link, or document reference...',
    recentCaptures: 'Recent Captures',
    recentProjects: 'Active Projects',
    allProjects: 'All Projects',
    createProject: 'Create Project',
    editProject: 'Edit Project',
    projectName: 'Project Name',
    projectDesc: 'Description',
    projectType: 'Project Type',
    defaultCategory: 'Default Category',
    importance: 'Importance',
    useCase: 'Use Case',
    saveSuccess: 'Successfully saved to project',
    aiAnalyzing: 'AI is analyzing...',
    emptyStateTitle: 'No sources captured yet',
    emptyStateDesc: 'Capture your first URL, GitHub repository, or document to start building project memory.',
    shareTitle: 'Save to Context OS',
    shareSubtitle: 'Analyze and index web resources directly into your project memories.',
    promptCopied: 'Prompt copied to clipboard!',
    copyPrompt: 'Copy Context Prompt',
    downloadMarkdown: 'Export as Markdown',
    overview: 'Overview',
    sources: 'Sources',
    knowledge: 'Knowledge Memory',
    relations: 'Relations Map',
    todo: 'Action Items',
    pendingAnalysis: 'Pending Analysis',
    completedAnalysis: 'Ready & Indexed',
    allPlatforms: 'All Platforms',
    allTypes: 'All Types',
    importanceFilter: 'Importance',
    statusFilter: 'Status',
    searchPlaceholder: 'Search by keyword, tags, category or project...',
    projectSelector: 'Choose Project',
    categorySelector: 'Choose Category',
    importanceSelector: 'Select Importance',
    useCaseSelector: 'Select Intended Use',
    analyzeNow: 'Analyze with AI Immediately',
    includeInContext: 'Include in Project Context',
    successToast: 'Resource successfully added to your knowledge base',
    exportHeaderTitle: 'Generate Project Context',
    exportHeaderDesc: 'Compile and pack selected sources into structured markdown prompts optimized for ChatGPT, Claude, Gemini, or Cursor.',
    totalProjects: 'Total Projects',
    totalSources: 'Captured Sources',
    readyContext: 'Ready Contexts',
    captureActivity: 'Captures Today',
    planFree: 'Free Plan',
    planPro: 'Pro Plan',
    planPower: 'Power (Enterprise) Plan',
    currentPlan: 'Current Plan',
    upgradeButton: 'Upgrade to Pro',
    pwaTitle: 'PWA & Mobile Setup',
    pwaDesc: 'Install Context OS as a standalone app to enable quick sharing targets on iOS and Android.',
  },
  'zh-TW': {
    brandName: 'Context OS',
    tagline: '專案記憶與 AI 語境管理器',
    dashboard: '今日概覽',
    projects: '專案列表',
    library: '資料庫',
    tags: '標籤管理',
    search: '搜尋',
    export: '匯出 Context',
    settings: '設定與帳戶',
    capture: '快速收藏',
    save: '儲存',
    addSource: '新增來源',
    quickCapture: '快速貼上網址',
    quickCapturePlaceholder: '貼上 YouTube / IG / TikTok / GitHub / 網頁網址...',
    recentCaptures: '最近新增的收藏',
    recentProjects: '最近使用的專案',
    allProjects: '所有專案',
    createProject: '建立新專案',
    editProject: '編輯專案',
    projectName: '專案名稱',
    projectDesc: '專案描述',
    projectType: '專案類型',
    defaultCategory: '預設分類',
    importance: '重要程度',
    useCase: '用途用途',
    saveSuccess: '已成功儲存到專案',
    aiAnalyzing: 'AI 正在進行深度分析與摘要...',
    emptyStateTitle: '尚無任何收藏資料',
    emptyStateDesc: '立即貼上第一個網址、GitHub 倉庫或筆記，開始建立專案的 AI 核心記憶。',
    shareTitle: '儲存至 Context OS',
    shareSubtitle: '直接將網路資源分析並索引至您的專案記憶中。',
    promptCopied: 'Prompt 已複製到剪貼簿！',
    copyPrompt: '複製 Context Prompt',
    downloadMarkdown: '匯出為 Markdown',
    overview: '總覽頁面',
    sources: '資料來源',
    knowledge: '知識記憶庫',
    relations: '資料關聯',
    todo: '待辦事項',
    pendingAnalysis: '待分析資料',
    completedAnalysis: '已完成索引',
    allPlatforms: '所有來源平台',
    allTypes: '所有資料類型',
    importanceFilter: '重要程度',
    statusFilter: '分析狀態',
    searchPlaceholder: '搜尋關鍵字、標籤、專案、備註或分類...',
    projectSelector: '選擇目標專案',
    categorySelector: '選擇資料分類',
    importanceSelector: '選擇重要程度',
    useCaseSelector: '選擇預期用途',
    analyzeNow: '立即啟動 AI 深度分析',
    includeInContext: '預設納入專案 Context 匯出',
    successToast: '資料已成功儲存至專案中',
    exportHeaderTitle: '建構專案 AI Context',
    exportHeaderDesc: '將已選取的資料來源打包並轉化為結構化語境 Prompt，無縫匯入 ChatGPT、Claude、Gemini 或 Cursor。',
    totalProjects: '專案總數',
    totalSources: '收藏總數',
    readyContext: '就緒 Context',
    captureActivity: '今日新增數量',
    planFree: '免費版 (Free)',
    planPro: '專業版 (Pro)',
    planPower: '終極 BYOK 版 (Power)',
    currentPlan: '目前方案',
    upgradeButton: '升級到專業版',
    pwaTitle: 'PWA 與手機桌面安裝',
    pwaDesc: '將 Context OS 安裝為獨立應用程式，解鎖 iOS/Android 原生分享選單快速儲存功能。',
  },
};

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Gamma GEX Option Trading',
    description: 'Dealer gamma positioning, market-maker hedging triggers, and options order flow indicators.',
    type: 'trading',
    color: '#4F46E5', // Indigo
    icon: 'TrendingUp',
    createdAt: '2026-06-01T10:00:00Z',
    updatedAt: '2026-07-08T15:30:00Z',
    sourceCount: 5,
    tags: ['GEX', 'Python', 'Trading', 'Options'],
    summary: 'A quantitative system tracking index option gamma profile curves to identify market support and resistance thresholds dictated by dealer hedging requirements.',
    status: 'in_progress'
  },
  {
    id: 'proj-2',
    name: 'Gemini Multi-Agent System',
    description: 'n8n workflow automated agent and server-side multi-model reasoning nodes.',
    type: 'software',
    color: '#0891B2', // Cyan
    icon: 'Cpu',
    createdAt: '2026-06-15T14:20:00Z',
    updatedAt: '2026-07-09T03:10:00Z',
    sourceCount: 4,
    tags: ['AI-Agent', 'Gemini', 'n8n', 'TypeScript'],
    summary: 'Server-side typescript environment orchestration leveraging Gemini Flash for rapid routing and Gemini Pro 1.5 for complex code reviews and workflow synthesis.',
    status: 'planning'
  },
  {
    id: 'proj-3',
    name: 'Content Marketing Reels Hook',
    description: 'High-performing short video visual structures, visual loops, and content engineering scripts.',
    type: 'content',
    color: '#DB2777', // Pink
    icon: 'Video',
    createdAt: '2026-07-01T09:00:00Z',
    updatedAt: '2026-07-09T04:50:00Z',
    sourceCount: 3,
    tags: ['Marketing', 'Shorts', 'TikTok', 'Instagram'],
    summary: 'Repository of viral attention-grabbing cues, narrative architectures, and typography timings derived from tech-focused YouTube Shorts and TikTok campaigns.',
    status: 'idea'
  }
];

export const INITIAL_SOURCES: Source[] = [
  {
    id: 'src-101',
    projectId: 'proj-1',
    title: 'Options Market Maker Gamma Hedging Mechanics',
    url: 'https://youtube.com/watch?v=GEX_Hedging_Mechanics_101',
    type: 'youtube',
    platform: 'youtube',
    category: 'Video Lecture',
    tags: ['GEX', 'Hedging', 'Options'],
    note: 'Excellent explanation of how zero-days-to-expiration (0DTE) option hedging amplifies intraday volatility spikes.',
    importance: 'high',
    useCase: '交易研究',
    aiSummary: 'This video dissects option market makers delta and gamma hedging dynamics. It highlights how heavy call-buying forces dealers to buy underlying futures to maintain delta neutrality, compressing volatility, while heavy put buying prompts rapid futures selling, accelerating market downturns.',
    aiKeyPoints: [
      'Gamma is highest when options are At-The-Money (ATM) and near expiration.',
      'Dealers in Long Gamma buy low and sell high to rehedge, stabilizing market fluctuations.',
      'Dealers in Short Gamma are forced to sell into declining markets and buy into rising ones, amplifying volatility.',
      '0DTE options concentrate dealer hedging into a highly compressed afternoon timeframe.'
    ],
    aiSuggestedTags: ['0DTE', 'DeltaNeutral', 'MarketMicrostructure'],
    aiRelations: ['src-102'],
    isAnalyzed: true,
    includeInContext: true,
    createdAt: '2026-07-05T12:00:00Z',
    updatedAt: '2026-07-05T12:05:00Z',
  },
  {
    id: 'src-102',
    projectId: 'proj-1',
    title: 'GEX-Tracker: Dealer Option Position Parser',
    url: 'https://github.com/quant-devs/gex-tracker-py',
    type: 'github',
    platform: 'github',
    category: 'Reference Code',
    tags: ['Python', 'Options', 'Trading'],
    note: 'Core algorithm for computing absolute gamma exposure across SPX strikes using CBOE end-of-day reports.',
    importance: 'critical',
    useCase: '程式參考',
    aiSummary: 'An open-source Python library designed to calculate and map market maker net GEX profile charts. It maps delta and gamma values strike-by-strike, interpolating historical implied volatility curves to calculate spot-move sensitivity curves.',
    aiKeyPoints: [
      'Integrates seamlessly with yfinance and Cboe live data feeds.',
      'Implements Black-Scholes Greek formulas vectorized inside Pandas.',
      'Plots cumulative GEX profiles with dynamic spot price intersections.',
      'Identifies the crucial "Gamma Flip" price zone where dealers shift from supportive hedging to volatility-amplifying hedging.'
    ],
    aiSuggestedTags: ['Pandas', 'BlackScholes', 'GammaFlip'],
    aiRelations: ['src-101'],
    isAnalyzed: true,
    includeInContext: true,
    createdAt: '2026-07-06T14:30:00Z',
    updatedAt: '2026-07-06T14:32:00Z',
  },
  {
    id: 'src-103',
    projectId: 'proj-1',
    title: 'Option Volatility Surface Interpolation Research Paper',
    url: 'https://arxiv.org/pdf/2405.12345.pdf',
    type: 'pdf',
    platform: 'pdf',
    category: 'Academic Research',
    tags: ['Trading', 'GEX'],
    note: 'Provides the formal cubic spline mathematical equations for option smiles smoothing.',
    importance: 'medium',
    useCase: '交易研究',
    aiSummary: 'A math-heavy paper introducing advanced spline interpolation techniques for option volatility grids. Solves the issue of empty strike points in thinly traded options to map an accurate, smooth risk landscape.',
    aiKeyPoints: [
      'Solves the arbitrage violations common in traditional linear interpolation.',
      'Maintains strictly positive probability density functions across all boundary conditions.',
      'Significantly improves the accuracy of localized delta calculations for deep Out-Of-The-Money options.'
    ],
    aiSuggestedTags: ['Math', 'Spline', 'ArbitrageFree'],
    aiRelations: [],
    isAnalyzed: true,
    includeInContext: false,
    createdAt: '2026-07-07T11:00:00Z',
    updatedAt: '2026-07-07T11:05:00Z',
  },
  {
    id: 'src-201',
    projectId: 'proj-2',
    title: 'Gemini SDK Tool Calling & Function Binding Protocols',
    url: 'https://api.google.com/gemini/docs/tool-calling',
    type: 'api',
    platform: 'api',
    category: 'API Documentation',
    tags: ['Gemini', 'TypeScript'],
    note: 'Official interface definition for passing client-side tools directly into GoogleGenAI clients.',
    importance: 'critical',
    useCase: 'API 文件',
    aiSummary: 'Detailed spec for schema declarations required to trigger function calls with Gemini. Shows how the model responds with structured JSON arguments indicating which local function to run before returning the payload.',
    aiKeyPoints: [
      'Requires strict JSON Schema object structures for parameters.',
      'Supports auto-execution with specific server frameworks or explicit client loops.',
      'Recommended model is gemini-2.5-flash for rapid schema verification, falling back to gemini-2.5-pro for complex multi-tool sequences.'
    ],
    aiSuggestedTags: ['SDK', 'JSONSchema', 'TypeScript'],
    aiRelations: [],
    isAnalyzed: true,
    includeInContext: true,
    createdAt: '2026-07-08T09:15:00Z',
    updatedAt: '2026-07-08T09:16:00Z',
  },
  {
    id: 'src-202',
    projectId: 'proj-2',
    title: 'Building an n8n AI Agent Workspace Tutorial',
    url: 'https://youtube.com/watch?v=n8n_Agent_Workflows_2026',
    type: 'youtube',
    platform: 'youtube',
    category: 'Tutorial Video',
    tags: ['AI-Agent', 'n8n'],
    note: 'Covers setting up advanced vector memory sub-nodes in custom self-hosted n8n instances.',
    importance: 'medium',
    useCase: '內容靈感',
    aiSummary: 'Step-by-step video configuration demonstrating n8n loops. Integrates webhook listeners that feed transcript files into a Gemini-powered summarizer node and save the resulting vectors.',
    aiKeyPoints: [
      'Utilizes PostgreSQL pgvector nodes for long-term agent memory.',
      'Handles rate-limiting gracefully by placing request throttling queues between agent calls.',
      'Shows how to dynamically inject prompt structures based on user intent routing nodes.'
    ],
    aiSuggestedTags: ['VectorDB', 'n8n', 'AgentWorkflows'],
    aiRelations: ['src-201'],
    isAnalyzed: true,
    includeInContext: true,
    createdAt: '2026-07-08T18:00:00Z',
    updatedAt: '2026-07-08T18:03:00Z',
  },
  {
    id: 'src-301',
    projectId: 'proj-3',
    title: 'Visual Retention Tactics in Tech Instagram Reels',
    url: 'https://instagram.com/p/Reels_Retention_Secrets_X',
    type: 'instagram',
    platform: 'instagram',
    category: 'Competitive Analysis',
    tags: ['Marketing', 'Instagram'],
    note: 'Deconstructs the first 3 seconds pacing of top Vercel and Linear visual update videos.',
    importance: 'high',
    useCase: 'UI 靈感',
    aiSummary: 'Deconstruction of high-engagement video hooks in SaaS marketing. Key findings focus on immediate high-contrast code edits, silent typewriter subtitle overlays, and rhythmic visual loops matching background beats.',
    aiKeyPoints: [
      'Hook: Immediate code terminal compilation success within the first 1.5 seconds.',
      'Symmetric visual loops prevent the viewer from sensing video wrap-around, inflating replay statistics.',
      'Text must occupy the upper-middle grid to avoid player interface overlays.'
    ],
    aiSuggestedTags: ['Reels', 'VisualHooks', 'MarketingStrategy'],
    aiRelations: [],
    isAnalyzed: true,
    includeInContext: true,
    createdAt: '2026-07-09T01:00:00Z',
    updatedAt: '2026-07-09T01:02:00Z',
  }
];

export const ALL_TAGS: Tag[] = [
  { id: 't-1', name: 'GEX', count: 3, color: '#4F46E5' },
  { id: 't-2', name: 'Python', count: 1, color: '#06B6D4' },
  { id: 't-3', name: 'Trading', count: 2, color: '#10B981' },
  { id: 't-4', name: 'Options', count: 2, color: '#6366F1' },
  { id: 't-5', name: 'AI-Agent', count: 2, color: '#F59E0B' },
  { id: 't-6', name: 'Gemini', count: 1, color: '#8B5CF6' },
  { id: 't-7', name: 'n8n', count: 1, color: '#EC4899' },
  { id: 't-8', name: 'TypeScript', count: 1, color: '#3B82F6' },
  { id: 't-9', name: 'Marketing', count: 1, color: '#EF4444' },
  { id: 't-10', name: 'Instagram', count: 1, color: '#D946EF' }
];

export const ALL_CATEGORIES: string[] = [
  'Video Lecture',
  'Reference Code',
  'Academic Research',
  'API Documentation',
  'Tutorial Video',
  'Competitive Analysis',
  'Design Assets',
  'Markdown Notes',
  'Prompts Specification'
];

// Real Category entities (id / name / projectId / count) seeded from the
// legacy flat list above. projectId is 'global' for categories shared across
// every project — per-project-only categories can be added later by giving
// them a real project id instead.
export const INITIAL_CATEGORIES: Category[] = ALL_CATEGORIES.map((name, idx) => ({
  id: `cat-${idx + 1}`,
  name,
  projectId: 'global',
  count: 0,
}));
